### ISSUE TITLE
Can't retrieve data splits for tasks

### ISSUE THREAD

**Issue by PGijsbers** [openml/OpenML#1108]
Downloading the datasplits for task 13854 and 14097 gives an error: `failed to perform action generate_folds. Evaluation Engine result send to EMAIL_API_LOG account.`
Direct link to splits file: [link](https://www.openml.org//api_splits/get/13854/Task_13854_splits.arff)

Openml-python gives the following traceback:
```python
import openml
task = openml.tasks.get_task(13854, download_qualities=False, download_data=False)
split = task.download_split()
```
```
Traceback (most recent call last):
  File "E:/repositories/openml-python/findsplits.py", line 34, in <module>
    split = task.download_split()
  File "E:\repositories\openml-python\openml\tasks\task.py", line 154, in download_split
    self._download_split(cached_split_file)
  File "E:\repositories\openml-python\openml\tasks\task.py", line 139, in _download_split
    openml._api_calls._download_text_file(
  File "E:\repositories\openml-python\openml\_api_calls.py", line 154, in _download_text_file
    response = __read_url(source, request_method="get", md5_checksum=md5_checksum)
  File "E:\repositories\openml-python\openml\_api_calls.py", line 205, in __read_url
    return _send_request(
  File "E:\repositories\openml-python\openml\_api_calls.py", line 257, in _send_request
    raise OpenMLServerError(
openml.exceptions.OpenMLServerError: Unexpected server error when calling https://www.openml.org//api_splits/get/13854/Task_13854_splits.arff. Please contact the developers!
Status code: 412
failed to perform action generate_folds. Evaluation Engine result send to EMAIL_API_LOG account.

Process finished with exit code 1
```

Issue first raised in [amlb#318](https://github.com/openml/automlbenchmark/issues/318).

**Comment by PGijsbers** [comment]
These tasks have custom splits.

**Comment by joaquinvanschoren** [comment]
We have to discontinue support for this specific type of task, at least for now. They were created a long time ago as an edge case and we can't maintain it in this form. We'll soon return an error when you ask for these tasks. Sorry about that.

Workaround: pick another existing task for that dataset that doesn't use a custom split file or create a new task (e.g. normal CV or holdout) through the API and use that one from now on.
IIRC, Pieter has already created these for the 2 tasks in the AutoML benchmark.

**Comment by PGijsbers** [comment]
New QSAR tasks are 360932 and 360933.

**Comment by PGijsbers** [comment]
I propose to close this issue and (if desired) open a new issue on bringing back support for custom splits.

**Comment by PGijsbers** [comment]
Closing this issue, the new error indicates that the tasks are deprecated (though there is the option to make it clearer).
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\repositories\openml-python\openml\utils.py", line 359, in safe_func
    return func(*args, **kwargs)
  File "D:\repositories\openml-python\openml\tasks\functions.py", line 376, in get_task
    raise e
  File "D:\repositories\openml-python\openml\tasks\functions.py", line 360, in get_task
    task = _get_task_description(task_id)
  File "D:\repositories\openml-python\openml\tasks\functions.py", line 389, in _get_task_description
    task_xml = openml._api_calls._perform_api_call("task/%d" % task_id, "get")
  File "D:\repositories\openml-python\openml\_api_calls.py", line 67, in _perform_api_call
    response = __read_url(url, request_method, data)
  File "D:\repositories\openml-python\openml\_api_calls.py", line 205, in __read_url
    return _send_request(
  File "D:\repositories\openml-python\openml\_api_calls.py", line 237, in _send_request
    __check_response(response=response, url=url, file_elements=files)
  File "D:\repositories\openml-python\openml\_api_calls.py", line 284, in __check_response
    raise __parse_server_exception(response, url, file_elements=file_elements)
openml.exceptions.OpenMLServerException: https://www.openml.org/api/v1/xml/task/13854 returned code 153: Deprecated task. This kind of task is no longer supported, please find or create a new task. - None
```
