### ISSUE TITLE
[Weka] API Exception: Problem validating uploaded description file

### ISSUE THREAD

**Issue by DraXus** [openml/OpenML#154]
I got this error when trying to run Task 1 with the following algorithm:

```
weka.classifiers.meta.FilteredClassifier -F "weka.filters.supervised.attribute.AttributeSelection -E \"weka.attributeSelection.PrincipalComponents -R 0.95 -A 5\" -S \"weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1\"" -W weka.classifiers.bayes.NaiveBayes
```

The error also appears with some other algorithms like:

```
weka.classifiers.meta.Vote -S 1 -B "weka.classifiers.trees.J48 -C 0.25 -M 2" -B "weka.classifiers.bayes.NaiveBayes " -B "weka.classifiers.rules.ZeroR " -R AVG -do-not-print
```

---
### Error Trace

```
Running experiment: Runs from: 1 to: 1
Datasets:
Custom property iterator: on
Custom property path:
1  weka.experiment.CrossValidationResultProducer::splitEvaluator ClassifierSplitEvaluator: weka.classifiers.rules.ZeroR (version 48055541465867954)
Custom property name:classifier
Custom property values:
 1 weka.classifiers.meta.FilteredClassifier FilteredClassifier: No model built yet.
ResultProducer: CrossValidationResultProducer: -X 10 -W org.openml.weka.experiment.TaskSplitEvaluator --: <null Instances>
ResultListener: org.openml.weka.experiment.TaskResultListener@33afc9b8

Writing experiment copy
Reading experiment copy
Made experiment copy
CrossValidationResultProducer: setting additional measures for split evaluator
[06-11-2014 10:49:11] [WARNING] [ARFF Cache] dataset dataset_1_anneal.arff hash and cache not identical: 
- Client: d01f6ccd68c88b749b20bbe897de3713
- Server: 08dc9d6bf8e5196de0d56bfc89631931
[06-11-2014 10:49:11] [INFO] [ARFF Cache] Stored dataset dataset_1_anneal.arff to cache. 
[06-11-2014 10:49:13] [INFO] [ARFF Cache] Loaded splits Task_1_splits.arff from cache. 
[06-11-2014 10:49:13] [INFO] [Splits] Obtaining folds for Task 1 (anneal) with weka.classifiers.meta.FilteredClassifier - Repeat 0
[06-11-2014 10:49:13] [INFO] [Splits] Folds obtained 
[06-11-2014 10:49:13] [INFO] [Perform Run] Started on performing Task 1 (anneal) with weka.classifiers.meta.FilteredClassifier - Repeat 0, fold 0
[06-11-2014 10:49:13] [INFO] [Build Model] Start building model on training data (808 instances)
[06-11-2014 10:49:13] [INFO] [Build Model] Done
[06-11-2014 10:49:13] [INFO] [Test Model] Start making predictions on test data (90 instances)
[06-11-2014 10:49:13] [INFO] [Test Model] Done
org.openml.apiconnector.io.ApiException: Problem validating uploaded description file
    org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:70)
    org.openml.apiconnector.io.OpenmlConnector.openmlImplementationUpload(OpenmlConnector.java:461)
    org.openml.weka.algorithm.WekaAlgorithm.getImplementationId(WekaAlgorithm.java:69)
    org.openml.weka.experiment.TaskResultListener$OpenmlExecutedTask.<init>(TaskResultListener.java:233)
    org.openml.weka.experiment.TaskResultListener.acceptResultsForSending(TaskResultListener.java:83)
    org.openml.weka.experiment.TaskResultProducer.doRun(TaskResultProducer.java:249)
    org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:173)
    org.openml.weka.gui.OpenmlRunPanel$ExperimentRunner.run(OpenmlRunPanel.java:197)

    at org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:70)
    at org.openml.apiconnector.io.OpenmlConnector.openmlImplementationUpload(OpenmlConnector.java:461)
    at org.openml.weka.algorithm.WekaAlgorithm.getImplementationId(WekaAlgorithm.java:69)
    at org.openml.weka.experiment.TaskResultListener$OpenmlExecutedTask.<init>(TaskResultListener.java:233)
    at org.openml.weka.experiment.TaskResultListener.acceptResultsForSending(TaskResultListener.java:83)
    at org.openml.weka.experiment.TaskResultProducer.doRun(TaskResultProducer.java:249)
    at org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:173)
    at org.openml.weka.gui.OpenmlRunPanel$ExperimentRunner.run(OpenmlRunPanel.java:197)
Done...
```

**Comment by joaquinvanschoren** [comment]
Seems to be working fine now. Closing.
