### ISSUE TITLE
[Weka] Class attribute is not nominal!

### ISSUE THREAD

**Issue by DraXus** [openml/OpenML#155]
I tried to run a supervised regression task using Linear Regression and got the following error. Are regression tasks supported in the current version of Weka plugin?

```
Running experiment: Runs from: 1 to: 1
Datasets:
Custom property iterator: on
Custom property path:
1  weka.experiment.CrossValidationResultProducer::splitEvaluator ClassifierSplitEvaluator: weka.classifiers.rules.ZeroR (version 48055541465867954)
Custom property name:classifier
Custom property values:
 1 weka.classifiers.functions.LinearRegression Linear Regression: No model built yet.
ResultProducer: CrossValidationResultProducer: -X 10 -W org.openml.weka.experiment.TaskSplitEvaluator --: <null Instances>
ResultListener: org.openml.weka.experiment.TaskResultListener@2b54d00e

Writing experiment copy
Reading experiment copy
Made experiment copy
CrossValidationResultProducer: setting additional measures for split evaluator
[06-11-2014 18:25:22] [INFO] [ARFF Cache] Stored dataset dataset_194_cleveland.arff to cache. 
[06-11-2014 18:25:25] [INFO] [ARFF Cache] Stored splits Task_2285_splits.arff to cache. 
[06-11-2014 18:25:25] [INFO] [Splits] Obtaining folds for Task 2285 (cleveland) with weka.classifiers.functions.LinearRegression - Repeat 0
[06-11-2014 18:25:25] [INFO] [Splits] Folds obtained 
[06-11-2014 18:25:25] [INFO] [Perform Run] Started on performing Task 2285 (cleveland) with weka.classifiers.functions.LinearRegression - Repeat 0, fold 0
java.lang.Exception: Class attribute is not nominal!
    org.openml.weka.experiment.TaskSplitEvaluator.getResult(TaskSplitEvaluator.java:63)
    org.openml.weka.experiment.TaskResultProducer.doRun(TaskResultProducer.java:222)
    org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:173)
    org.openml.weka.gui.OpenmlRunPanel$ExperimentRunner.run(OpenmlRunPanel.java:197)

    at org.openml.weka.experiment.TaskSplitEvaluator.getResult(TaskSplitEvaluator.java:63)
    at org.openml.weka.experiment.TaskResultProducer.doRun(TaskResultProducer.java:222)
    at org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:173)
    at org.openml.weka.gui.OpenmlRunPanel$ExperimentRunner.run(OpenmlRunPanel.java:197)
Done...
```

**Comment by joaquinvanschoren** [comment]
I believe this was fixed a while ago? Please reopen if still an issue.
