### ISSUE TITLE
[Weka] IndexOutOfBoundsException when obtaining folds

### ISSUE THREAD

**Issue by DraXus** [openml/OpenML#172]
The following error is shown when trying to run task 17 in Weka 3.7.12 using Naive Bayes as classifier.

[14-02-2015 13:41:27] [INFO] [ARFF Cache] Stored dataset 17 to cache. 
[14-02-2015 13:41:27] [INFO] [ARFF Cache] Stored splits 17 to cache. 
[14-02-2015 13:41:27] [INFO] [Splits] Obtaining folds for Task 17 (bridges) with weka.classifiers.bayes.NaiveBayes - Repeat 0
java.lang.IndexOutOfBoundsException: Index: 107, Size: 107
    java.util.ArrayList.rangeCheck(ArrayList.java:635)
    java.util.ArrayList.get(ArrayList.java:411)
    weka.core.Instances.instance(Instances.java:768)
    org.openml.weka.experiment.TaskResultProducer.doRun(TaskResultProducer.java:248)
    org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:173)
    org.openml.weka.gui.OpenmlRunPanel$ExperimentRunner.run(OpenmlRunPanel.java:197)

```
at java.util.ArrayList.rangeCheck(ArrayList.java:635)
at java.util.ArrayList.get(ArrayList.java:411)
at weka.core.Instances.instance(Instances.java:768)
at org.openml.weka.experiment.TaskResultProducer.doRun(TaskResultProducer.java:248)
at org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:173)
at org.openml.weka.gui.OpenmlRunPanel$ExperimentRunner.run(OpenmlRunPanel.java:197)
```

**Comment by joaquinvanschoren** [comment]
Hi Manuel,

How did you run weka? Did you use the standalone version of the website of
did you use the package manager to install the plugin?

@Jan: Can we now remove the standalone version from the website and use the
package from now on?

Thanks,
Joaquin

**Comment by joaquinvanschoren** [comment]
@Manuel: did you try clearing the cache? We did a lot of changes in the
caching mechanism recently.

The cache is in a .openml folder in your home dir.

Cheers,
Joaquin

**Comment by DraXus** [comment]
It was a clean standalone Weka version and then I installed the OpenML plugin from the package repository. I only got that error with tasks using dataset 17 so far. I tried to clean the cache but it happened again.

**Comment by joaquinvanschoren** [comment]
Interesting. Jan, can you take a look?

**Comment by DraXus** [comment]
I mean, it's not urgent. I will use other datasets for the demo, but just take a look when you can :)

**Comment by joaquinvanschoren** [comment]
We have released several new versions of the apiconnector in the mean time. Please check if this is still an issue.

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/java#15
