### ISSUE TITLE
Task 4788 is broken

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/OpenML#698]
When I try downloading the task in R I get:

```
> tsk <- getOMLTask(task.id = 4788)
Task '4788' file 'task.xml' found in cache.
Task '4788' file 'datasplits.arff' found in cache.
Data '414' file 'description.xml' found in cache.
Data '414' file 'dataset.arff' found in cache.
Error in .jnew("weka/core/Instances", .jcast(reader, "java/io/Reader")) : 
  java.io.IOException: keyword @relation expected, read Token[=====], line 1
> traceback()
8: stop(list(message = "java.io.IOException: keyword @relation expected, read Token[=====], line 1", 
       call = .jnew("weka/core/Instances", .jcast(reader, "java/io/Reader")), 
       jobj = <S4 object of class "jobjRef">))
7: .External(RcreateObject, class, ..., silent = silent)
6: .jnew("weka/core/Instances", .jcast(reader, "java/io/Reader"))
5: RWeka::read.arff(file)
4: arff.reader(f$datasplits.arff$path)
3: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
2: suppressWarnings(arff.reader(f$datasplits.arff$path))
1: getOMLTask(task.id = 4788)
```

There appear to be similar problems in python.

**Comment by PGijsbers** [comment]
Python input:

```
import openml
t = openml.tasks.get_task(4788)
```

output:
```
Traceback (most recent call last):
  File "D:\repositories\openml-python\openml\tasks\task.py", line 79, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "D:\repositories\openml-python\openml\tasks\split.py", line 81, in _from_arff_file
    splits, meta = scipy.io.arff.loadarff(filename)
  File "C:\Users\s105307\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\io\arff\arffread.py", line 539, in loadarff
    ofile = open(f, 'rt')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\s105307/.openml/cache\\tasks\\4788\\datasplits.arff'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\repositories\openml-python\openml\tasks\functions.py", line 293, in get_task
    raise e
  File "D:\repositories\openml-python\openml\tasks\functions.py", line 289, in get_task
    task.download_split()
  File "D:\repositories\openml-python\openml\tasks\task.py", line 85, in download_split
    split = OpenMLSplit._from_arff_file(cached_split_file)
  File "D:\repositories\openml-python\openml\tasks\split.py", line 81, in _from_arff_file
    splits, meta = scipy.io.arff.loadarff(filename)
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\io\arff\arffread.py", line 541, in loadarff
    return _loadarff(ofile)
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\io\arff\arffread.py", line 550, in _loadarff
    rel, attr = read_header(ofile)
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\io\arff\arffread.py", line 344, in read_header
    i = next(ofile)
StopIteration
```
