### ISSUE TITLE
Unexpected server error. Please contact the developers! Status code: 500

### ISSUE THREAD

**Issue by hildeweerts** [openml/OpenML#714]
When running a bunch of experiments at the same time, I sometimes get the following error for a few seconds:
```
Unexpected server error. Please contact the developers!
Status code: 500
```
I am running experiments for the random forest on one big machine with 72 cores. Especially with small datasets the models are built extremely fast, so I suspect the server might be unable to handle all the requests. At the same time I am also running experiments for svm in a batch with five 4 core machines.

**Comment by hildeweerts** [comment]
It happens _before_ building the model btw. So it probably has to do with querying whether the run already exists or not.

**Comment by hildeweerts** [comment]
And sometimes also when trying to download a task.

**Comment by janvanrijn** [comment]
Thanks for reporting this. 

For debugging information, can you provide
* The URL that was being called that failed
* The OpenML error code (if you got anything beyond the 500)

**Comment by hildeweerts** [comment]
An example of the traceback:
```
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)

xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/xmltodict.py", line 309, in parse
    parser.ParseFile(xml_input)
  File "/Users/hildeweerts/hyperimp/experiment_1/hyperimp/experiment/experiment.py", line 38, in run_experiment
    run = train_model(task, classifier)
TypeError: argument must have 'read' attribute
  File "/Users/hildeweerts/hyperimp/experiment_1/hyperimp/utils/misc.py", line 26, in inner
    return async_result.get(timeout)

During handling of the above exception, another exception occurred:

  File "/Users/hildeweerts/anaconda/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
Traceback (most recent call last):
  File "/Users/hildeweerts/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 133, in _parse_server_exception
    server_exception = xmltodict.parse(response.text)
  File "/Users/hildeweerts/hyperimp/experiment_1/hyperimp/experiment/experiment.py", line 31, in train_model
    run = openml.runs.run_model_on_task(task, classifier)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/runs/functions.py", line 40, in run_model_on_task
    flow_tags=flow_tags, seed=seed)

During handling of the above exception, another exception occurred:

  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/runs/functions.py", line 84, in run_flow_on_task
    setup_id = setup_exists(flow_from_server, flow.model)
Traceback (most recent call last):
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/setups/functions.py", line 52, in setup_exists
    file_elements=file_elements)
  File "/Users/hildeweerts/hyperimp/experiment_1/hyperimp/experiment/experiment.py", line 38, in run_experiment
    run = train_model(task, classifier)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 53, in _perform_api_call
    file_elements=file_elements)
  File "/Users/hildeweerts/hyperimp/experiment_1/hyperimp/utils/misc.py", line 26, in inner
    return async_result.get(timeout)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 100, in _read_url_files
    raise _parse_server_exception(response, url=url)
  File "/Users/hildeweerts/anaconda/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 137, in _parse_server_exception
    '%d\n' % response.status_code) + response.text)
  File "/Users/hildeweerts/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
openml.exceptions.OpenMLServerError: Unexpected server error. Please contact the developers!
Status code: 500

  File "/Users/hildeweerts/hyperimp/experiment_1/hyperimp/experiment/experiment.py", line 31, in train_model
    run = openml.runs.run_model_on_task(task, classifier)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/runs/functions.py", line 40, in run_model_on_task
    flow_tags=flow_tags, seed=seed)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/runs/functions.py", line 83, in run_flow_on_task
    flow_from_server = get_flow(flow_id)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/flows/functions.py", line 25, in get_flow
    flow_xml = _perform_api_call("flow/%d" % flow_id)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 54, in _perform_api_call
    return _read_url(url, data)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 122, in _read_url
    raise _parse_server_exception(response, url=url)
  File "/Users/hildeweerts/anaconda/lib/python3.6/site-packages/openml/_api_calls.py", line 137, in _parse_server_exception
    '%d\n' % response.status_code) + response.text)
```

**Comment by janvanrijn** [comment]
If you were to catch the errors and rety the API call after, say, 30 seconds, does that solve things?

Just asking as that might indicate a sever load issue and help us alleviate the problem.

**Comment by hildeweerts** [comment]
Yeah, I was thinking the same thing. I'm considering to add some randomness into the number of seconds to make sure all tasks that failed don't retry at exactly the same time, if that makes any sense.

Are there any other reasons you know of that can cause an OpenMLServerError? Just to make sure I do not end up in some infinite loop of retries.

**Comment by janvanrijn** [comment]
It are usually the complicated queries. If you log which API calls are the worst we can look at them on an 1 by 1 basis
