### ISSUE TITLE
error fetching zoo dataset: IndexError in sklearn.datasets.openml._convert_arff_data

### ISSUE THREAD

**Issue by azrdev** [openml/OpenML#989]
~~~python
>>> import sklearn.datasets
>>> sklearn.datasets.fetch_openml( 'zoo')
/usr/lib/python3.7/site-packages/sklearn/datasets/openml.py:305: UserWarning: Multiple active versions of the dataset matching the name zoo exist. Versions may be fundamentally different, returning version 1.
  " {version}.".format(name=name, version=res[0]['version']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/sklearn/datasets/openml.py", line 643, in fetch_openml
    X, y = _convert_arff_data(arff['data'], col_slice_x, col_slice_y, shape)
  File "/usr/lib/python3.7/site-packages/sklearn/datasets/openml.py", line 249, in _convert_arff_data
    y = data[:, col_slice_y]
IndexError: index 17 is out of bounds for axis 1 with size 17
~~~

#### Versions

~~~
Linux-5.1.11-arch1-1-ARCH-x86_64-with-arch
Python 3.7.3 (default, Jun 24 2019, 04:54:02) 
[GCC 9.1.0]
NumPy 1.16.4
SciPy 1.3.0
Scikit-Learn 0.21.2

ModuleNotFoundError: No module named 'openml'
~~~

**Comment by joaquinvanschoren** [comment]
Is this a sklearn issue or an OpenML issue?
From the looks of it you are fetching through sklearn without installing
OpenML.

**Comment by azrdev** [comment]
> From the looks of it you are fetching through sklearn without installing OpenML.

correct, reported there as https://github.com/scikit-learn/scikit-learn/issues/14340

**Comment by amueller** [comment]
looks like an inconsistency in the dataset. The qualities say there's 17 features, but there's actually 18 in the dataset. The target has index 17, which, according to the qualities, doesn't exist.

**Comment by amueller** [comment]
ah it's because ``animal`` is ignored, so our bug

**Comment by joaquinvanschoren** [comment]
OK, can we close this issue?
